# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


# this  iw widget for user data
# on it would be displayed basic information about the user and user image
# in the future would be nice to add personalisation possibility and change password and change account
class Ui_Form(object):
    def setupUi(self, Form, user):
        self.user = user
        Form.setObjectName("Form")
        Form.resize(540, 400)
        Form.setStyleSheet("background-color: rgb(146,170,157);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 60, 250, 300))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 70, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(270, 140, 70, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(270, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.user_name = QtWidgets.QLabel(Form)
        self.user_name.setGeometry(QtCore.QRect(350, 80, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.user_name.setFont(font)
        self.user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name.setObjectName("user_name")
        self.user_email = QtWidgets.QLabel(Form)
        self.user_email.setGeometry(QtCore.QRect(350, 140, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.user_email.setFont(font)
        self.user_email.setAlignment(QtCore.Qt.AlignCenter)
        self.user_email.setObjectName("user_email")
        self.user_password = QtWidgets.QLabel(Form)
        self.user_password.setGeometry(QtCore.QRect(350, 200, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.user_password.setFont(font)
        self.user_password.setAlignment(QtCore.Qt.AlignCenter)
        self.user_password.setObjectName("user_password")
        self.user_date = QtWidgets.QLabel(Form)
        self.user_date.setGeometry(QtCore.QRect(350, 260, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.user_date.setFont(font)
        self.user_date.setAlignment(QtCore.Qt.AlignCenter)
        self.user_date.setObjectName("user_date")

        # displays user image
        self.pixmap = QPixmap('photos/user.jpg')
        self.label.setPixmap(self.pixmap)
        self.label.setScaledContents(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Email"))
        self.label_4.setText(_translate("Form", "Password"))
        self.label_5.setText(_translate("Form", "Join Date"))
        self.user_name.setText(_translate("Form", f"{self.user.name}"))
        self.user_password.setText(_translate("Form", f"{self.user.password}"))
        self.user_email.setText(_translate("Form", f"{self.user.email}"))
        self.user_date.setText(_translate("Form", f"{self.user.join_date}"))
