# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, product, reviews):
        self.product = product
        Form.setObjectName("Form")
        Form.resize(619, 436)
        Form.setStyleSheet("background-color: rgb(146,170,157);")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 341, 351))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 340, 350))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.grade_label = QtWidgets.QLabel(Form)
        self.grade_label.setGeometry(QtCore.QRect(480, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.grade_label.setFont(font)
        self.grade_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.grade_label.setObjectName("grade_label")
        self.grade = QtWidgets.QSlider(Form)
        self.grade.setGeometry(QtCore.QRect(390, 80, 191, 22))
        self.grade.setMinimum(0)
        self.grade.setMaximum(10)
        self.grade.setPageStep(1)
        self.grade.setProperty("value", 5)
        self.grade.setOrientation(QtCore.Qt.Horizontal)
        self.grade.setObjectName("grade")
        self.textBrowser = QtWidgets.QTextEdit(Form)
        self.textBrowser.setGeometry(QtCore.QRect(370, 130, 231, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(510, 380, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(208, 219, 189);")
        self.pushButton.setObjectName("pushButton")

        if len(reviews) != 0:
            self.avg_grade = round(sum([reviews[i][0] for i in range(len(reviews))])/len(reviews), 1)
            height = 5
            for review in reviews:
                label = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
                if len(review[1]) > 40:
                    label.setGeometry(QtCore.QRect(10, height, 320, 100))
                    height += 105
                else:
                    label.setGeometry(QtCore.QRect(10, height, 320, 50))
                    height += 55
                label.setText(f'Grade: {review[0]}\n{review[1]}')
                label.setFont(font)
        else:
            self.avg_grade = "No grade yet"
            label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            label.setGeometry(QtCore.QRect(10, 5, 320, 30))
            label.setText('No reviews yet')
            label.setFont(font)



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", f"Reviews For {self.product}"))
        self.grade_label.setText(_translate("Form", f"Grade: {self.avg_grade}"))
        self.pushButton.setText(_translate("Form", "Add Review"))


# if __name__ == "__main__":
#     import sys
#     product_name = 'Asus Zenbook'
#     product_id = '9a19f051-d52e-11ec-b7fe-e884a5fda5dd'
#     reviews = [[9, 'Piorfect'], [7, 'I was expecting more, very warm proc']]
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form, product_name, product_id, reviews)
#     Form.show()
#     sys.exit(app.exec_())
